version: "3"
services:
  database:
    image: "postgis/postgis"
    container_name: approved-premises-postgres-dev
    environment:
      - POSTGRES_USER=localdev
      - POSTGRES_PASSWORD=localdev_password
      - POSTGRES_DB=approved_premises_localdev
    volumes:
      - database-data-development:/var/lib/postgresql/data/
    ports:
      - "5431:5432"

  hmpps-auth:
    image: quay.io/hmpps/hmpps-auth:latest
    container_name: hmpps-auth
    ports:
      - "9091:8080"
    healthcheck:
      test:
        [ "CMD", "curl", "-f", "http://localhost:8080/auth/health" ]
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - APPLICATION_AUTHENTICATION_UI_ALLOWLIST=0.0.0.0/0
      - SPRING_H2_CONSOLE_SETTINGS_WEBALLOWOTHERS=true

  community-api:
    image: quay.io/hmpps/community-api:latest
    container_name: community-api
    ports:
      - "9590:8080"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
    environment:
      - SERVER_PORT=8080
      - SPRING_PROFILES_ACTIVE=dev
      - SPRING_H2_CONSOLE_SETTINGS_WEBALLOWOTHERS=true
      - ALFRESCO_BASEURL=http://wiremock:8080/alfresco

  hmpps-assess-risks-and-needs:
    image: quay.io/hmpps/hmpps-assess-risks-and-needs
    container_name: assess-risks-and-needs
    ports:
      - "9580:8080"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
    environment:
      - SERVER_PORT=8080
      - SPRING_PROFILES_ACTIVE=oasys-rsr,dev
      - OAUTH_ENDPOINT_URL=http://hmpps-auth:8080/auth
      - ASSESSMENT-API_BASE-URL=http://wiremock:8080
      - COMMUNITY-API_BASE-URL=http://community-api:8080

  wiremock:
    image: rodolpheche/wiremock
    container_name: wiremock
    ports:
      - "9004:8080"
    volumes:
      - ./wiremock:/home/wiremock

  prison-api:
    image: quay.io/hmpps/prison-api:latest
    container_name: prison-api
    ports:
      - "9570:8080"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/health" ]
    environment:
      - SERVER_PORT=8080
      - SPRING_PROFILES_ACTIVE=nomis-hsqldb
      - SPRING_DATASOURCE_URL=jdbc:hsqldb:file:/nomis-db/nomisdb;sql.syntax_ora=true;get_column_name=false;shutdown=false;sql.nulls_first=false;sql.nulls_order=false;hsqldb.lock_file=false
      - SPRING_DATASOURCE_USERNAME=sa
      - SPRING_DATASOURCE_PASSWORD=password
      - SPRING_REPLICA_DATASOURCE_URL=jdbc:hsqldb:file:/nomis-db/nomisdb;sql.syntax_ora=true;get_column_name=false;shutdown=false;sql.nulls_first=false;sql.nulls_order=false;hsqldb.lock_file=false
      - SPRING_REPLICA_DATASOURCE_USERNAME=sa
      - SPRING_REPLICA_DATASOURCE_PASSWORD=password
    volumes:
      - ./nomis-db:/nomis-db

  redis:
    image: "bitnami/redis:5.0"
    container_name: approved-premises-redis-dev
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - "6379:6379"

  localstack:
    image: localstack/localstack:1.3.1
    container_name: approved-premises-api-localstack
    ports:
      - "4566:4566"
      - "4571:4571"
      - 8999:8080
    environment:
      - SERVICES=sns,sqs
      - DEBUG=${DEBUG- }
      - DOCKER_HOST=unix:///var/run/docker.sock
      - DEFAULT_REGION=eu-west-2
    volumes:
      - "${TMPDIR:-/tmp/localstack}:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"

volumes:
  database-data-development:
