version: "3"
services:
  integration_test_database:
    image: "postgis/postgis"
    environment:
      - POSTGRES_USER=integration_test
      - POSTGRES_PASSWORD=integration_test_password
      - POSTGRES_DB=approved_premises_integration_test
    ports:
      - "5433:5432"

  integration_test_redis:
    image: "bitnami/redis:7.0.11"
    container_name: approved-premises-redis-test
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - "6377:6379"

  localstack:
    image: localstack/localstack:1.3.1
    container_name: approved-premises-api-test-localstack
    ports:
      - "4566:4566"
      - "4571:4571"
      - 8999:8080
    environment:
      - SERVICES=sns,sqs
      - DEBUG=${DEBUG- }
      - DOCKER_HOST=unix:///var/run/docker.sock
      - DEFAULT_REGION=eu-west-2
    volumes:
      - "${TMPDIR:-/tmp/localstack}:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
