version: "3"
services:
  database:
    image: "postgres"
    environment:
      - POSTGRES_USER=localdev
      - POSTGRES_PASSWORD=localdev_password
      - POSTGRES_DB=approved_premises_localdev
    volumes:
      - database-data-development:/var/lib/postgresql/data/
    ports:
      - "5431:5432"

  hmpps-auth:
    image: quay.io/hmpps/hmpps-auth:latest
    ports:
      - "9091:8080"
    healthcheck:
      test:
        [ "CMD", "curl", "-f", "http://localhost:8080/auth/health" ]
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - APPLICATION_AUTHENTICATION_UI_ALLOWLIST=0.0.0.0/0
      - SPRING_H2_CONSOLE_SETTINGS_WEBALLOWOTHERS=true

  community-api:
    image: quay.io/hmpps/community-api:latest
    ports:
      - "9590:8080"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
    environment:
      - SERVER_PORT=8080
      - SPRING_PROFILES_ACTIVE=dev
      - SPRING_H2_CONSOLE_SETTINGS_WEBALLOWOTHERS=true

  hmpps-assess-risks-and-needs:
    image: quay.io/hmpps/hmpps-assess-risks-and-needs
    ports:
      - "9580:8080"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
    environment:
      - SERVER_PORT=8080
      - SPRING_PROFILES_ACTIVE=oasys-rsr,dev
      - OAUTH_ENDPOINT_URL=http://hmpps-auth:8080/auth
      - ASSESSMENT-API_BASE-URL=http://wiremock:8080
      - COMMUNITY-API_BASE-URL=http://community-api:8080

  wiremock:
    image: rodolpheche/wiremock
    ports:
      - "9004:8080"
    volumes:
      - ./wiremock:/home/wiremock

  prison-api:
    image: quay.io/hmpps/prison-api:latest
    container_name: prison-api
    ports:
      - "9570:8080"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/health" ]
    environment:
      - SERVER_PORT=8080
      - SPRING_PROFILES_ACTIVE=nomis-hsqldb
      - SPRING_DATASOURCE_URL=jdbc:hsqldb:file:/nomis-db/nomisdb;sql.syntax_ora=true;get_column_name=false;shutdown=false;sql.nulls_first=false;sql.nulls_order=false;hsqldb.lock_file=false
      - SPRING_DATASOURCE_USERNAME=sa
      - SPRING_DATASOURCE_PASSWORD=password
    volumes:
      - ./nomis-db:/nomis-db

  redis:
    image: "bitnami/redis:5.0"
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - "6380:6379"

volumes:
  database-data-development:
