spring:
  datasource:
    username: localdev
    password: localdev_password
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5431/approved_premises_localdev
  jpa:
    database: postgresql

