info.app:
  name: Approved Premises Api
  version: 1.0

spring:
  application:
    name: approved-premises-api
  codec:
    max-in-memory-size: 10MB

  jackson:
    date-format: "yyyy-MM-dd HH:mm:ss"
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false

  profiles:
    group:
      test:
        - "stdout"

  flyway:
    repeatable-sql-migration-prefix: "R"
    sql-migration-prefix: ""
    outOfOrder: true
    locations: classpath:db/migration/all,classpath:db/migration/all-except-integration
    placeholderReplacement: true

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.spatial.dialect.postgis.PostgisDialect

  redis:
    database: 5
    timeout: 60000
    ssl: false

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${hmpps.auth.url}/.well-known/jwks.json
      client:
        registration:
          delius-backed-apis:
            provider: hmpps-auth
            client-id: approved-premises-api
            client-secret: clientsecret
            authorization-grant-type: client_credentials
          hmpps-tier:
            provider: hmpps-auth
            client-id: approved-premises-api
            client-secret: clientsecret
            authorization-grant-type: client_credentials
          prisons-api:
            provider: hmpps-auth
            client-id: approved-premises-api
            client-secret: clientsecret
            authorization-grant-type: client_credentials
          case-notes:
            provider: hmpps-auth
            client-id: approved-premises-api
            client-secret: clientsecret
            authorization-grant-type: client_credentials
          ap-oasys-context:
            provider: hmpps-auth
            client-id: approved-premises-api
            client-secret: clientsecret
            authorization-grant-type: client_credentials
        provider:
          hmpps-auth:
            token-uri: ${hmpps.auth.url}/oauth/token

springdoc:
  swagger-ui:
    urls:
      - name: API
        url: "api.yml"
      - name: Domain events
        url: "domain-events-api.yml"

server:
  port: 8080
  servlet:
    context-path: /
  forward-headers-strategy: native
  tomcat:
    remoteip:
      remote-ip-header: x-forwarded-for
      protocol-header: x-forwarded-proto
      internal-proxies: 10\.\d{1,3}\.\d{1,3}\.\d{1,3}|192\.168\.\d{1,3}\.\d{1,3}|169\.254\.\d{1,3}\.\d{1,3}|127\.\d{1,3}\.\d{1,3}\.\d{1,3}|172\.1[6-9]{1}\.\d{1,3}\.\d{1,3}|172\.2[0-9]{1}\.\d{1,3}\.\d{1,3}|172\.3[0-1]{1}\.\d{1,3}\.\d{1,3}|0:0:0:0:0:0:0:1|::1|100\.6[4-9]\.\d{1,3}\.\d{1,3}|100\.[7-9][0-9]{1}\.\d{1,3}\.\d{1,3}|100\.1[0-1][0-9]{1}\.\d{1,3}\.\d{1,3}|100\.12[0-7]\.\d{1,3}\.\d{1,3}
  shutdown: graceful
  error:
    include-message: always

management:
  endpoints:
    web:
      base-path: /
      exposure:
        include: 'info, health'
  endpoint:
    health:
      cache:
        time-to-live: 2000ms
      show-components: always
      show-details: always
      probes:
        enabled: true
    info:
      cache:
        time-to-live: 2000ms

services:
  community-api:
    base-url: http://localhost:9590
  hmpps-tier:
    base-url: http://localhost:9004
  prisons-api:
    base-url: http://localhost:9570
  case-notes:
    base-url: http://localhost:9004
  ap-delius-context-api:
    base-url: http://localhost:9004
  ap-oasys-context-api:
    base-url: http://localhost:9004
  gov-uk-bank-holidays-api:
    base-url: https://www.gov.uk

hmpps:
  auth:
    url: http://localhost:9091/auth

log-client-credentials-jwt-info: false

prison-case-notes:
  lookback-days: 365
  prison-api-page-size: 30
  excluded-categories:
    - category: MOVED_CELL
      subcategory: null
    - category: TRANSFER
      subcategory: null
    - category: SENTENCE
      subcategory: null
    - category: PRISON
      subcategory: RELEASE

prison-adjudications:
  prison-api-page-size: 30

caches:
  staffMembers:
    expiry-seconds: 21600
  staffMember:
    expiry-seconds: 21600
  userAccess:
    expiry-seconds: 1200
  staffDetails:
    expiry-seconds: 1200
  teamManagingCases:
    expiry-seconds: 21600
  ukBankHolidays:
    expiry-seconds: 86400
  jwks:
    expiry-seconds: 14400

seed:
  file-prefix: "/tmp/seed"

assign-default-region-to-users-with-unknown-region: false

url-templates:
  api:
    application-submitted-event-detail: http://localhost:3000/events/application-submitted/#eventId
    application-assessed-event-detail: http://localhost:3000/events/application-assessed/#eventId
    booking-made-event-detail: http://localhost:3000/events/booking-made/#eventId
    person-arrived-event-detail: http://localhost:3000/events/person-arrived/#eventId
    person-not-arrived-event-detail: http://localhost:3000/events/person-not-arrived/#eventId
    person-departed-event-detail: http://localhost:3000/events/person-departed/#eventId
    booking-not-made-event-detail: http://localhost:3000/events/booking-not-made/#eventId
    booking-cancelled-event-detail: http://localhost:3000/events/booking-cancelled/#eventId
    booking-changed-event-detail: http://localhost:3000/events/booking-changed/#eventId
    application-withdrawn-event-detail: http://localhost:3000/events/application-withdrawn/#eventId
  frontend:
    application: http://localhost:3000/applications/#id
    assessment: http://localhost:3000/assessments/#id
    booking: http://localhost:3000/premises/{premisesId}/bookings/{bookingId}

preemptive-cache-key-prefix: ""
preemptive-cache-logging-enabled: false
preemptive-cache-delay-ms: 10000
preemptive-cache-lock-duration-ms: 120000
