spring:
  datasource:
    username: localdev
    password: localdev_password
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5431/approved_premises_localdev
  flyway:
    locations: classpath:db/migration/all,classpath:db/migration/local+dev+test,classpath:db/migration/local,classpath:db/migration/all-except-integration
  jpa:
    database: postgresql
  redis:
    host: localhost
    port: 6379
    password: ""

hmpps.sqs:
  provider: localstack
  topics:
    domainevents:
      arn: arn:aws:sns:eu-west-2:000000000000:domainevents

domain-events:
  cas1:
    emit-enabled: true
  cas2:
    emit-enabled: true
  cas3:
    emit-enabled: bookingCancelled,bookingConfirmed,bookingProvisionallyMade,personArrived,personDeparted,referralSubmitted

log-client-credentials-jwt-info: true

seed:
  file-prefix: "./seed"
  auto:
    enabled: true
    file-prefixes: classpath:db/seed/local+dev+test

assign-default-region-to-users-with-unknown-region: true
preemptive-cache-logging-enabled: true
