spring:
  datasource:
    username: localdev
    password: localdev_password
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5431/approved_premises_localdev
  jpa:
    database: postgresql

hmpps:
  auth:
    url: http://localhost:9091/auth
    client-id: approved-premises-api
    client-secret: clientsecret
