spring:
  datasource:
    username: localdev
    password: localdev_password
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5431/approved_premises_localdev
  flyway:
    locations: classpath:db/migration/all,classpath:db/migration/local+dev
  jpa:
    database: postgresql
  redis:
    host: localhost
    port: 6380
    password: ""

log-client-credentials-jwt-info: true
