openapi: '3.0.1'
info:
  version: '0.1.0'
  title: 'CAS3 Domain events'
  description: Get information about events in the CAS3 domain
paths:
  /events/cas3/booking-cancelled/{eventId}:
    parameters:
      - name: eventId
        description: UUID of the event
        in: path
        required: true
        schema:
          $ref: '#/components/schemas/EventId'
    get:
      tags:
        - "CAS3 events"
      summary: A 'booking-cancelled' event
      responses:
        200:
          description: The 'booking-cancelled' event corresponding to the provided `eventId`
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CAS3BookingCancelledEvent'
        404:
          description: No 'booking-cancelled' event found for the provided `eventId`
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Problem'
        500:
          $ref: '#/components/responses/500Response'
  /events/cas3/booking-cancelled-updated/{eventId}:
    parameters:
      - name: eventId
        description: UUID of the event
        in: path
        required: true
        schema:
          $ref: '#/components/schemas/EventId'
    get:
      tags:
        - "CAS3 events"
      summary: A 'booking-cancelled-updated' event
      responses:
        200:
          description: The 'booking-cancelled-updated' event corresponding to the provided `eventId`
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CAS3BookingCancelledUpdatedEvent'
        404:
          description: No 'booking-cancelled-updated' event found for the provided `eventId`
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Problem'
        500:
          $ref: '#/components/responses/500Response'
  /events/cas3/booking-confirmed/{eventId}:
    parameters:
      - name: eventId
        description: UUID of the event
        in: path
        required: true
        schema:
          $ref: '#/components/schemas/EventId'
    get:
      tags:
        - "CAS3 events"
      summary: A 'booking-confirmed' event
      responses:
        200:
          description: The 'booking-confirmed' event corresponding to the provided `eventId`
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CAS3BookingConfirmedEvent'
        404:
          description: No 'booking-confirmed' event found for the provided `eventId`
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Problem'
        500:
          $ref: '#/components/responses/500Response'
  /events/cas3/booking-provisionally-made/{eventId}:
    parameters:
      - name: eventId
        description: UUID of the event
        in: path
        required: true
        schema:
          $ref: '#/components/schemas/EventId'
    get:
      tags:
        - "CAS3 events"
      summary: A 'booking-provisionally-made' event
      responses:
        200:
          description: The 'booking-provisionally-made' event corresponding to the provided `eventId`
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CAS3BookingProvisionallyMadeEvent'
        404:
          description: No 'person-arrived' event found for the provided `eventId`
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Problem'
        500:
          $ref: '#/components/responses/500Response'
  /events/cas3/person-arrived/{eventId}:
    parameters:
      - name: eventId
        description: UUID of the event
        in: path
        required: true
        schema:
          $ref: '#/components/schemas/EventId'
    get:
      tags:
        - "CAS3 events"
      summary: A 'person-arrived' event
      responses:
        200:
          description: The 'person-arrived' event corresponding to the provided `eventId`
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CAS3PersonArrivedEvent'
        404:
          description: No 'person-arrived' event found for the provided `eventId`
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Problem'
        500:
          $ref: '#/components/responses/500Response'
  /events/cas3/person-arrived-updated/{eventId}:
    parameters:
      - name: eventId
        description: UUID of the event
        in: path
        required: true
        schema:
          $ref: '#/components/schemas/EventId'
    get:
      tags:
        - "CAS3 events"
      summary: A 'person-arrived-updated' event
      responses:
        200:
          description: The 'person-arrived-updated' event corresponding to the provided `eventId`
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CAS3PersonArrivedUpdatedEvent'
        404:
          description: No 'person-arrived-updated' event found for the provided `eventId`
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Problem'
        500:
          $ref: '#/components/responses/500Response'
  /events/cas3/person-departed/{eventId}:
    parameters:
      - name: eventId
        description: UUID of the event
        in: path
        required: true
        schema:
          $ref: '#/components/schemas/EventId'
    get:
      tags:
        - "CAS3 events"
      summary: A 'person-departed' event
      responses:
        200:
          description: The 'person-departed' event corresponding to the provided `eventId`
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CAS3PersonDepartedEvent'
        404:
          description: No 'person-departed' event found for the provided `eventId`
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Problem'
        500:
          $ref: '#/components/responses/500Response'
  /events/cas3/referral-submitted/{eventId}:
    parameters:
      - name: eventId
        description: UUID of the event
        in: path
        required: true
        schema:
          $ref: '#/components/schemas/EventId'
    get:
      tags:
        - "CAS3 events"
      summary: A 'referral-submitted' event
      responses:
        200:
          description: The 'referral-submitted' event corresponding to the provided `eventId`
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CAS3ReferralSubmittedEvent'
        404:
          description: No 'referral-submitted' event found for the provided `eventId`
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Problem'
        500:
          $ref: '#/components/responses/500Response'
  /events/cas3/person-departure-updated/{eventId}:
    parameters:
      - name: eventId
        description: UUID of the event
        in: path
        required: true
        schema:
          $ref: '#/components/schemas/EventId'
    get:
      tags:
        - "CAS3 events"
      summary: A 'person-departure-updated' event
      responses:
        200:
          description: The 'person-departure-updated' event corresponding to the provided `eventId`
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CAS3PersonDepartureUpdatedEvent'
        404:
          description: No 'person-departure-updated' event found for the provided `eventId`
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Problem'
        500:
          $ref: '#/components/responses/500Response'
components:
  responses:
    500Response:
      description: unexpected error
      content:
        'application/json':
          schema:
            $ref: '#/components/schemas/Problem'
  schemas:
    CAS3Event:
      type: object
      properties:
        id:
          $ref: '#/components/schemas/EventId'
        timestamp:
          type: string
          example: '2022-11-30T14:53:44'
          format: date-time
        eventType:
          $ref: '#/components/schemas/EventType'
      required:
        - id
        - timestamp
        - eventType
      discriminator:
        propertyName: eventType
        mapping:
          accommodation.cas3.booking.cancelled: '#/components/schemas/CAS3BookingCancelledEvent'
          accommodation.cas3.booking.cancelled.updated: '#/components/schemas/CAS3BookingCancelledUpdatedEvent'
          accommodation.cas3.booking.confirmed: '#/components/schemas/CAS3BookingConfirmedEvent'
          accommodation.cas3.booking.provisionally-made: '#/components/schemas/CAS3BookingProvisionallyMadeEvent'
          accommodation.cas3.person.arrived: '#/components/schemas/CAS3PersonArrivedEvent'
          accommodation.cas3.person.arrived.updated: '#/components/schemas/CAS3PersonArrivedUpdatedEvent'
          accommodation.cas3.person.departed: '#/components/schemas/CAS3PersonDepartedEvent'
          accommodation.cas3.referral.submitted: '#/components/schemas/CAS3ReferralSubmittedEvent'
          accommodation.cas3.person.departed.updated: '#/components/schemas/CAS3PersonDepartureUpdatedEvent'
          accommodation.cas3.assessment.updated: '#/components/schemas/CAS3AssessmentUpdatedEvent'
    CAS3BookingCancelledEvent:
      allOf:
        - $ref: '#/components/schemas/CAS3Event'
        - type: object
          properties:
            eventDetails:
              $ref: '#/components/schemas/CAS3BookingCancelledEventDetails'
          required:
            - eventDetails
    CAS3BookingCancelledUpdatedEvent:
      allOf:
        - $ref: '#/components/schemas/CAS3Event'
        - type: object
          properties:
            eventDetails:
              $ref: '#/components/schemas/CAS3BookingCancelledEventDetails'
          required:
            - eventDetails
    CAS3BookingCancelledEventDetails:
      type: object
      properties:
        personReference:
          $ref: '#/components/schemas/PersonReference'
        applicationId:
          type: string
          format: uuid
        applicationUrl:
          type: string
          format: uri
        bookingId:
          type: string
          format: uuid
        bookingUrl:
          type: string
          format: uri
        cancellationReason:
          type: string
        cancelledAt:
          type: string
          format: date
        notes:
          type: string
        cancelledBy:
          $ref: '#/components/schemas/StaffMember'
      required:
        - personReference
        - bookingId
        - bookingUrl
        - cancellationReason
    CAS3BookingConfirmedEvent:
      allOf:
        - $ref: '#/components/schemas/CAS3Event'
        - type: object
          properties:
            eventDetails:
              $ref: '#/components/schemas/CAS3BookingConfirmedEventDetails'
          required:
            - eventDetails
    CAS3BookingConfirmedEventDetails:
      type: object
      properties:
        personReference:
          $ref: '#/components/schemas/PersonReference'
        applicationId:
          type: string
          format: uuid
        applicationUrl:
          type: string
          format: uri
        bookingId:
          type: string
          format: uuid
        bookingUrl:
          type: string
          format: uri
        expectedArrivedAt:
          type: string
          format: date-time
        notes:
          type: string
        confirmedBy:
          $ref: '#/components/schemas/StaffMember'
      required:
        - personReference
        - bookingId
        - bookingUrl
        - expectedArrivedAt
        - notes
    CAS3BookingProvisionallyMadeEvent:
      allOf:
        - $ref: '#/components/schemas/CAS3Event'
        - type: object
          properties:
            eventDetails:
              $ref: '#/components/schemas/CAS3BookingProvisionallyMadeEventDetails'
          required:
            - eventDetails
    CAS3BookingProvisionallyMadeEventDetails:
      type: object
      properties:
        personReference:
          $ref: '#/components/schemas/PersonReference'
        applicationId:
          type: string
          format: uuid
        applicationUrl:
          type: string
          format: uri
        bookingId:
          type: string
          format: uuid
        bookingUrl:
          type: string
          format: uri
        expectedArrivedAt:
          type: string
          format: date-time
        notes:
          type: string
        bookedBy:
          $ref: '#/components/schemas/StaffMember'
      required:
        - personReference
        - bookingId
        - bookingUrl
        - expectedArrivedAt
        - notes
    CAS3PersonArrivedEvent:
      allOf:
        - $ref: '#/components/schemas/CAS3Event'
        - type: object
          properties:
            eventDetails:
              $ref: '#/components/schemas/CAS3PersonArrivedEventDetails'
          required:
            - eventDetails
    CAS3PersonArrivedUpdatedEvent:
      allOf:
        - $ref: '#/components/schemas/CAS3Event'
        - type: object
          properties:
            eventDetails:
              $ref: '#/components/schemas/CAS3PersonArrivedEventDetails'
          required:
            - eventDetails
    CAS3PersonArrivedEventDetails:
      type: object
      properties:
        personReference:
          $ref: '#/components/schemas/PersonReference'
        deliusEventNumber:
          type: string
        applicationId:
          type: string
          format: uuid
        applicationUrl:
          type: string
          format: uri
        bookingId:
          type: string
          format: uuid
        bookingUrl:
          type: string
          format: uri
        premises:
          $ref: '#/components/schemas/Cas3DomainEventPremises'
        arrivedAt:
          type: string
          format: date-time
        expectedDepartureOn:
          type: string
          format: date
        notes:
          type: string
        recordedBy:
          $ref: '#/components/schemas/StaffMember'
      required:
        - personReference
        - deliusEventNumber
        - bookingId
        - bookingUrl
        - premises
        - arrivedAt
        - expectedDepartureOn
        - notes
    CAS3PersonDepartedEvent:
      allOf:
        - $ref: '#/components/schemas/CAS3Event'
        - type: object
          properties:
            eventDetails:
              $ref: '#/components/schemas/CAS3PersonDepartedEventDetails'
          required:
            - eventDetails
    CAS3PersonDepartureUpdatedEvent:
      allOf:
        - $ref: '#/components/schemas/CAS3Event'
        - type: object
          properties:
            eventDetails:
              $ref: '#/components/schemas/CAS3PersonDepartedEventDetails'
          required:
            - eventDetails
    CAS3PersonDepartedEventDetails:
      type: object
      properties:
        personReference:
          $ref: '#/components/schemas/PersonReference'
        deliusEventNumber:
          type: string
        applicationId:
          type: string
          format: uuid
        applicationUrl:
          type: string
          format: uri
        bookingId:
          type: string
          format: uuid
        bookingUrl:
          type: string
          format: uri
        premises:
          $ref: '#/components/schemas/Cas3DomainEventPremises'
        departedAt:
          type: string
          format: date-time
        reason:
          type: string
        reasonDetail:
          type: string
        notes:
          type: string
        recordedBy:
          $ref: '#/components/schemas/StaffMember'
      required:
        - personReference
        - deliusEventNumber
        - bookingId
        - bookingUrl
        - premises
        - departedAt
        - reason
        - notes
    CAS3ReferralSubmittedEvent:
      allOf:
        - $ref: '#/components/schemas/CAS3Event'
        - type: object
          properties:
            eventDetails:
              $ref: '#/components/schemas/CAS3ReferralSubmittedEventDetails'
          required:
            - eventDetails
    CAS3ReferralSubmittedEventDetails:
      type: object
      properties:
        personReference:
          $ref: '#/components/schemas/PersonReference'
        applicationId:
          type: string
          format: uuid
        applicationUrl:
          type: string
          format: uri
      required:
        - personReference
        - applicationId
        - applicationUrl
    CAS3AssessmentUpdatedEvent:
      allOf:
        - $ref: '#/components/schemas/CAS3Event'
      type: object
      properties:
        updatedFields:
          type: array
          items:
           $ref: '#/components/schemas/CAS3AssessmentUpdatedField'
      required:
        - updatedFields
    CAS3AssessmentUpdatedField:
      type: object
      properties:
        fieldName:
          type: string
        updatedFrom:
          type: string
        updatedTo:
          type: string
      required:
        - fieldName
        - updatedFrom
        - updatedTo
    # Common domain schemas
    PersonReference:
      type: object
      properties:
        crn:
          type: string
        noms:
          type: string
      required:
        - crn

    Cas3DomainEventPremises:
      type: object
      properties:
        addressLine1:
          type: string
        addressLine2:
          type: string
        postcode:
          type: string
        town:
          type: string
        region:
          type: string
      required:
        - addressLine1
        - postcode
        - region

    # Utility schemas
    EventId:
      description: The UUID of an event
      type: string
      format: uuid
      example: 364145f9-0af8-488e-9901-b4c46cd9ba37
    EventType:
      description: The type of an event
      type: string
      enum:
        - accommodation.cas3.booking.cancelled
        - accommodation.cas3.booking.cancelled.updated
        - accommodation.cas3.booking.confirmed
        - accommodation.cas3.booking.provisionally-made
        - accommodation.cas3.person.arrived
        - accommodation.cas3.person.arrived.updated
        - accommodation.cas3.person.departed
        - accommodation.cas3.referral.submitted
        - accommodation.cas3.person.departed.updated
        - accommodation.cas3.assessment.updated
      x-enum-varnames:
        - bookingCancelled
        - bookingCancelledUpdated
        - bookingConfirmed
        - bookingProvisionallyMade
        - personArrived
        - personArrivedUpdated
        - personDeparted
        - referralSubmitted
        - personDepartureUpdated
        - assessmentUpdated
    Problem:
      type: object
      properties:
        type:
          type: string
          example: https://example.net/validation-error
        title:
          type: string
          example: Invalid request parameters
        status:
          type: integer
          example: 400
        detail:
          type: string
          example: You provided invalid request parameters
        instance:
          type: string
          example: f7493e12-546d-42c3-b838-06c12671ab5b
    StaffMember:
      description: A member of probation or HPT staff detail
      type: object
      properties:
        staffCode:
          type: string
          example: N54A999
        username:
          type: string
          example: JohnSmithNPS
        probationRegionCode:
          type: string
          example: N53
      required:
        - staffCode
        - username
        - probationRegionCode