openapi: 3.0.1
info:
  version: 1.0.1
  title: 'Transitional Accommodation Services (CAS3)'
servers:
  - url: /cas3
paths:
  /reports/{reportName}:
    get:
      tags:
        - CAS3 Reports
      summary: Returns a spreadsheet of all data metrics for the 'reportName'.
      operationId: reportsReportNameGet
      parameters:
        - name: reportName
          in: path
          description: Name of the report to download
          required: true
          schema:
            $ref: '_shared.yml#/components/schemas/Cas3ReportType'
        - name: probationRegionId
          in: query
          required: false
          description: If provided, only this region will be returned
          schema:
            type: string
            format: uuid
        - name: startDate
          in: query
          required: true
          description: Start of date range to return
          example: '2024-02-21'
          schema:
            type: string
            format: date
        - name: endDate
          in: query
          required: true
          description: End of date range to return
          example: '2024-02-21'
          schema:
            type: string
            format: date
      responses:
        200:
          description: Successfully retrieved the report
          content:
            'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet':
              schema:
                type: string
                format: binary
  /timeline/{assessmentId}:
    get:
      operationId: getTimelineEntries
      tags:
        - CAS3
      summary: Returns the timeline entries for a given Assessment.
      parameters:
        - name: assessmentId
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        200:
          description: Successfully retrieved the timeline events
          content:
            'application/json':
              schema:
                type: array
                items:
                  $ref: '_shared.yml#/components/schemas/ReferralHistoryNote'
  /applications/{applicationId}:
    delete:
      operationId: deleteApplication
      tags:
        - Operations on application
      summary: Soft delete a draft application
      parameters:
        - name: applicationId
          in: path
          description: Id of the application
          required: true
          schema:
            type: string
            format: uuid
      responses:
        200:
          description: successful operation
        400:
          description: invalid params
          content:
            'application/problem+json':
              schema:
                $ref: '_shared.yml#/components/schemas/ValidationError'


