---
# Per environment values which override defaults in approved-premises-api/values.yaml

generic-service:
  serviceAccountName: hmpps-community-accommodation-api-service-account

  resources:
    limits:
      memory: 1.5Gi
    requests:
      memory: 1Gi


  ingress:
    host: approved-premises-api.hmpps.service.justice.gov.uk
    tlsSecretName: hmpps-approved-premises-api-prod-cert

  env:
    JAVA_OPTS: "-Xmx1000m"
    SPRING_PROFILES_ACTIVE: prod
    APPLICATIONINSIGHTS_CONFIGURATION_FILE: applicationinsights.json
    HMPPS_AUTH_URL: https://sign-in.hmpps.service.justice.gov.uk/auth
    SERVICES_COMMUNITY-API_BASE-URL: https://community-api-secure.probation.service.justice.gov.uk
    SERVICES_AP-DELIUS-CONTEXT-API_BASE-URL: https://approved-premises-and-delius.hmpps.service.justice.gov.uk
    SERVICES_ASSESS-RISKS-AND-NEEDS-API_BASE-URL: https://assess-risks-and-needs.hmpps.service.justice.gov.uk
    SERVICES_HMPPS-TIER_BASE-URL: https://hmpps-tier.hmpps.service.justice.gov.uk
    SERVICES_PRISONS-API_BASE-URL: https://api.prison.service.justice.gov.uk
    SERVICES_NOMIS-USER-ROLES-API_BASE-URL: https://nomis-user.aks-live-1.studio-hosting.service.justice.gov.uk
    SERVICES_CASE-NOTES_BASE-URL: https://offender-case-notes.service.justice.gov.uk
    SERVICES_AP-OASYS-CONTEXT-API_BASE-URL: https://approved-premises-and-oasys.hmpps.service.justice.gov.uk
    SERVICES_GOV-UK-BANK-HOLIDAYS-API_BASE-URL: https://www.gov.uk
    SPRING_FLYWAY_LOCATIONS: classpath:db/migration/all,classpath:db/migration/all-except-integration
    LOG-CLIENT-CREDENTIALS-JWT-INFO: false
    SENTRY_ENVIRONMENT: prod
    CACHES_STAFFMEMBERS_EXPIRY-SECONDS: 300
    DOMAIN-EVENTS_EMIT-ENABLED: true
    NOTIFY_MODE: ENABLED
    HMPPS_SQS_USE_WEB_TOKEN: true
    MANUAL_BOOKINGS_DOMAIN_EVENTS_DISABLED: false

    URL-TEMPLATES_FRONTEND_APPLICATION: https://approved-premises.hmpps.service.justice.gov.uk/applications/#id
    URL-TEMPLATES_FRONTEND_ASSESSMENT: https://approved-premises.hmpps.service.justice.gov.uk/assessments/#id
    URL-TEMPLATES_FRONTEND_BOOKING: https://approved-premises.hmpps.service.justice.gov.uk/premises/#premisesId/bookings/#bookingId
    URL-TEMPLATES_API_APPLICATION-SUBMITTED-EVENT-DETAIL: https://approved-premises-api.hmpps.service.justice.gov.uk/events/application-submitted/#eventId
    URL-TEMPLATES_API_APPLICATION-ASSESSED-EVENT-DETAIL: https://approved-premises-api.hmpps.service.justice.gov.uk/events/application-assessed/#eventId
    URL-TEMPLATES_API_BOOKING-MADE-EVENT-DETAIL: https://approved-premises-api.hmpps.service.justice.gov.uk/events/booking-made/#eventId
    URL-TEMPLATES_API_PERSON-ARRIVED-EVENT-DETAIL: https://approved-premises-api.hmpps.service.justice.gov.uk/events/person-arrived/#eventId
    URL-TEMPLATES_API_PERSON-NOT-ARRIVED-EVENT-DETAIL: https://approved-premises-api.hmpps.service.justice.gov.uk/events/person-not-arrived/#eventId
    URL-TEMPLATES_API_PERSON-DEPARTED-EVENT-DETAIL: https://approved-premises-api.hmpps.service.justice.gov.uk/events/person-departed/#eventId
    URL-TEMPLATES_API_BOOKING-NOT-MADE-EVENT-DETAIL: https://approved-premises-api.hmpps.service.justice.gov.uk/events/booking-not-made/#eventId
    URL-TEMPLATES_API_BOOKING-CANCELLED-EVENT-DETAIL: https://approved-premises-api.hmpps.service.justice.gov.uk/events/booking-cancelled/#eventId
    URL-TEMPLATES_API_BOOKING-CHANGED-EVENT-DETAIL: https://approved-premises-api.hmpps.service.justice.gov.uk/events/booking-changed/#eventId
    URL-TEMPLATES_API_APPLICATION-WITHDRAWN-EVENT-DETAIL: https://approved-premises-api.hmpps.service.justice.gov.uk/events/application-withdrawn/#eventId
    ARRIVED-DEPARTED-DOMAIN-EVENTS-DISABLED: true

  namespace_secrets:
    hmpps-domain-events-topic:
      HMPPS_SQS_TOPICS_DOMAINEVENTS_ARN: "topic_arn"
    hmpps-approved-premises-api:
      NOTIFY_APIKEY: "NOTIFY_APIKEY"
