---
# Per environment values which override defaults in approved-premises-api/values.yaml

generic-service:
  replicaCount: 2

  ingress:
    host: approved-premises-api-dev.hmpps.service.justice.gov.uk
    tlsSecretName: hmpps-approved-premises-api-dev-cert

  env:
    SPRING_PROFILES_ACTIVE: dev
    APPLICATIONINSIGHTS_CONFIGURATION_FILE: applicationinsights.nonprod.json
    HMPPS_AUTH_URL: https://sign-in-dev.hmpps.service.justice.gov.uk/auth
    SERVICES_COMMUNITY-API_BASE-URL: https://community-api-secure.test.delius.probation.hmpps.dsd.io
    SERVICES_AP-DELIUS-CONTEXT-API_BASE-URL: https://approved-premises-and-delius-dev.hmpps.service.justice.gov.uk
    SERVICES_HMPPS-TIER_BASE-URL: https://hmpps-tier-dev.hmpps.service.justice.gov.uk
    SERVICES_PRISONS-API_BASE-URL: https://api-dev.prison.service.justice.gov.uk
    SERVICES_CASE-NOTES_BASE-URL: https://dev.offender-case-notes.service.justice.gov.uk
    SERVICES_AP-OASYS-CONTEXT-API_BASE-URL: https://approved-premises-and-oasys-dev.hmpps.service.justice.gov.uk
    SERVICES_GOV-UK-BANK-HOLIDAYS-API_BASE-URL: https://www.gov.uk
    SPRING_FLYWAY_LOCATIONS: classpath:db/migration/all,classpath:db/migration/local+dev,classpath:db/migration/all-except-integration
    LOG-CLIENT-CREDENTIALS-JWT-INFO: true
    ASSIGN-DEFAULT-REGION-TO-USERS-WITH-UNKNOWN-REGION: true
    SENTRY_ENVIRONMENT: dev
    CACHES_STAFFMEMBERS_EXPIRY-SECONDS: 20
    APPLICATION-URL-TEMPLATE: https://approved-premises-dev.hmpps.service.justice.gov.uk/applications/#id
    APPLICATION-SUBMITTED-DETAIL-URL-TEMPLATE: https://approved-premises-api-dev.hmpps.service.justice.gov.uk/events/application-submitted/#eventId
    APPLICATION-ASSESSED-DETAIL-URL-TEMPLATE: https://approved-premises-api-dev.hmpps.service.justice.gov.uk/events/application-assessed/#eventId
    BOOKING-MADE-DETAIL-URL-TEMPLATE: https://approved-premises-api-dev.hmpps.service.justice.gov.uk/events/booking-made/#eventId
    PERSON-ARRIVED-DETAIL-URL-TEMPLATE: https://approved-premises-api-dev.hmpps.service.justice.gov.uk/events/person-arrived/#eventId
    PERSON-NOT-ARRIVED-DETAIL-URL-TEMPLATE: https://approved-premises-api-dev.hmpps.service.justice.gov.uk/events/person-not-arrived/#eventId
    PERSON-DEPARTED-DETAIL-URL-TEMPLATE: https://approved-premises-api-dev.hmpps.service.justice.gov.uk/events/person-departed/#eventId
    BOOKING-NOT-MADE-DETAIL-URL-TEMPLATE: https://approved-premises-api-dev.hmpps.service.justice.gov.uk/events/booking-not-made/#eventId
    DOMAIN-EVENTS_EMIT-ENABLED: true
    PREEMPTIVE-CACHE-LOGGING-ENABLED: true
    PREEMPTIVE-CACHE-DELAY-MS: 60000

  namespace_secrets:
    hmpps-domain-events-topic:
      HMPPS_SQS_TOPICS_DOMAINEVENTS_ARN: "topic_arn"
      HMPPS_SQS_TOPICS_DOMAINEVENTS_ACCESS_KEY_ID: "access_key_id"
      HMPPS_SQS_TOPICS_DOMAINEVENTS_SECRET_ACCESS_KEY: "secret_access_key"

  allowlist:
    unilink-aovpn1: "194.75.210.216/29"
    unilink-aovpn2: "83.98.63.176/29"
    unilink-aovpn3: "78.33.10.50/31"
    unilink-aovpn4: "78.33.10.52/30"
    unilink-aovpn5: "78.33.10.56/30"
    unilink-aovpn6: "78.33.10.60/32"
    unilink-aovpn7: "78.33.32.99/32"
    unilink-aovpn8: "78.33.32.100/30"
    unilink-aovpn9: "78.33.32.104/30"
    unilink-aovpn10: "78.33.32.108/32"
    unilink-aovpn11: "217.138.45.109/32"
    unilink-aovpn12: "217.138.45.110/32"
    ncc-tsc-team-1: "5.148.32.192/26"
    ncc-tsc-team-2: "5.148.69.16/28"
    ncc-tsc-team-3: "31.221.110.80/29"
    ncc-tsc-team-4: "154.51.64.64/27"
    ncc-tsc-team-5: "154.51.128.224/27"
    ncc-tsc-team-6: "167.98.1.160/28"
    ncc-tsc-team-7: "167.98.25.176/28"
    ncc-tsc-team-8: "167.98.200.192/27"
    ncc-tsc-team-9: "195.95.131.0/24"
    ncc-mvss-team-1: "5.148.8.192/26"

# CloudPlatform AlertManager receiver to route prometheus alerts to slack
# See https://user-guide.cloud-platform.service.justice.gov.uk/documentation/monitoring-an-app/how-to-create-alarms.html#creating-your-own-custom-alerts
generic-prometheus-alerts:
  alertSeverity: hmpps-approved-premises
