name: CI

on:
  pull_request:
  merge_group:
  push:
    branches:
      - main
      - develop

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - uses: satackey/action-docker-layer-caching@v0.0.11
        continue-on-error: true

      - run: docker-compose -f docker-compose.test.yml up -d

      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 18

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Lint
        id: lint
        run: ./gradlew ktlintCheck

      - name: Test
        id: test
        run: ./gradlew test
